[package]
name = "gitaly-error"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json = "1.0"
thiserror.workspace = true
tonic.workspace = true
