http_listen_addr = "0.0.0.0:8080"
ssh_listen_addr = "0.0.0.0:2222"
gitaly_addr = "http://127.0.0.1:2305"

[auth]
gitaly_token = "dev-secret"
client_tokens = ["dev-token"]
ssh_public_keys = ["ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAoWL1H1e2kxmtS2+87Ax6SSS1XBcpZcmE3E7nmAnmvGa2ImUxMFSt1/EzL1xQDgv/iavw0vtElrO+K/IynhUWfatzsNfD1cFPbTa2vmh0c1mYwQKgA9AOwSCmyZn5bctaUUqQITBN2LQXEPFWaJi3spPaoli8HjC0gTZKLMJG0tAMPTtdSvI/ngTG3I1tml6fHCGhDEJnPQQuCngprksZKVMKV9Wtocdc/wpZt2JjuNbYiu0SCLP0/64ka64hFf2sXzzhQAQTlTUMMc7ijEtkpAIt8cBGgQNbYgxkbE5YczWGebyKzJmkykYjGp68AofHelCB2jeolJ+5txRFuXaUFQ== fcoury@macbook.local"]

[repositories]
storage_name = "default"
