[package]
name = "gitaly-storage"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
redb.workspace = true
serde.workspace = true
serde_json = "1.0"
thiserror.workspace = true
tokio.workspace = true
